version: "3.8"
services:
  # server:
  #   build: 
  #     context: ./server
  #     network: host
  #   volumes: 
  #   - $PWD/server:/app/
  #   ports: 
  #   - 3001:8080
  #   entrypoint: ["uvicorn", "app:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]

  frontend:
    build: 
      context: ./frontend
      network: host
      dockerfile: dev.Dockerfile
    volumes: 
    - ./frontend:/app
    ports:
    - 3002:3000